source :rubygems
#ruby '1.9.2'

gem 'rake'
gem 'nats', '=0.4.22'
gem 'netaddr'
gem 'blobstore_client', '~> 0.3.13'
gem 'posix-spawn'
gem 'ruby-atmos-pure'
gem 'sigar', ">=0.7.2"
gem 'uuidtools'
gem 'yajl-ruby', require: 'yajl/json_gem'
gem 'json'
gem 'agent_client'
gem 'bosh_common'
gem 'rest-client'
gem 'ruby-graphviz'

git 'git://github.com/cloudfoundry/bosh.git' do
  gem 'monit_api'
  gem 'bosh_encryption'
  #gem 'bosh_agent'
end

gem 'bosh_agent', require: 'agent'

group :console do
  gem 'highline'
  gem 'progressbar'
  gem 'statemachine'
end

group :web do
  gem 'sinatra', require: 'sinatra/base'
  gem 'thin'
  gem 'rack'
  gem 'rack-rewrite'
end

group :assets do
  gem 'sprockets'
  gem 'coffee-script'
  gem 'uglifier'
end

group :test do
  gem 'rspec', '>= 2.12.0'
  gem 'rcov', platforms: :ruby_18
  gem 'ci_reporter'
  gem 'simplecov', platforms: :ruby_19
  gem 'simplecov-rcov', platforms: :ruby_19
  gem 'fakeweb'
  gem 'rack-test', require: 'rack/test'
end

group :development do
  gem 'shotgun'
  gem 'jasmine'
  gem 'execjs'
  gem 'therubyracer'
end
