require 'rake'
require 'erb'

require 'rspec/core/rake_task'

desc "Run specs"
task "spec" => ["test:spec"]

desc "Run specs using RCov"
task "spec:rcov" => ["bundler:install:test", "test:spec:rcov"]

desc "Run specs for CI"
task "spec:ci" => ["bundler:install:test", "test:spec:ci"]

namespace "assets" do
  desc "Precompile assets"
  task "precompile" do
    Bundler.require
    js_path = File.expand_path("../public/assets/js/*.coffee", __FILE__)
    Dir[js_path].each do |file|
      content = CoffeeScript.compile File.read(file)
      File.open(file.gsub('.coffee', '.js'), "w") { |f| f.write(content) }
    end
  end
end

namespace "bundler" do
  desc "Install gems"
  task "install" do
    sh("bundle install")
  end

  desc "Install gems for test"
  task "install:test" do
    sh("bundle install --local --without development production")
  end

  desc "Install gems for production"
  task "install:production" do
    sh("bundle install --local --without development test")
  end

  desc "Install gems for development"
  task "install:development" do
    sh("bundle install --local --without test production")
  end
end

namespace "test" do

  RSpec::Core::RakeTask.new(:spec)

  task "spec:ci" do |t|
    sh("cd spec && rake spec:ci")
  end

  task "spec:rcov" do |t|
    sh("cd spec && rake spec:rcov")
  end

end



begin
  require 'jasmine'
  load 'jasmine/tasks/jasmine.rake'
rescue LoadError
  task :jasmine do
    abort "Jasmine is not available. In order to run jasmine, you must: (sudo) gem install jasmine"
  end
end
